config/routes.rb
EquipmentTracker::Application.routes.draw do
  resources :users

  get "users/new"

  get "home/index"
  get "equipment/new"

  resources :equipment
  
  root :to => 'equipment#index'

end

app/models/equipment.rb
# == Schema Information
#
# Table name: equipment
#
#  id                          :integer         not null, primary key
#  equipment_id                :string(255)
#  model_number                :string(255)
#  serial_number               :string(255)
#  location                    :string(255)
#  equipment_description       :text
#  use                         :text
#  department                  :string(255)
#  po_number                   :string(255)
#  pm_required                 :string(255)
#  maintenance_frequency       :string(255)
#  maintenance_sop             :string(255)
#  calibration_required        :boolean
#  calibration_frequency       :string(255)
#  calibration_date            :date
#  calibration_sticker         :boolean
#  calibration_database_update :boolean
#  calibration_specs           :string(255)
#  validation_required         :boolean
#  validation_sop              :string(255)
#  validation_document         :string(255)
#  validation_approval         :string(255)
#  created_at                  :datetime        not null
#  updated_at                  :datetime        not null
#  avatar_file_name            :string(255)
#  avatar_content_type         :string(255)
#  avatar_file_size            :integer
#  avatar_updated_at           :datetime
#  sop_file_name               :string(255)
#  sop_content_type            :string(255)
#  sop_file_size               :integer
#  sop_updated_at              :datetime
#

class Equipment < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  
  has_attached_file :sop
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/new
  # GET /equipment/new.json
  def new
    @equipment = Equipment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/1/edit
  def edit
    @equipment = Equipment.find(params[:id])
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(params[:equipment])

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
        format.json { render json: @equipment, status: :created, location: @equipment }
      else
        format.html { render action: "new" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /equipment/1
  # PUT /equipment/1.json
  def update
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      if @equipment.update_attributes(params[:equipment])
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy

    respond_to do |format|
      format.html { redirect_to equipment_index_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def logo
    logo = image_tag("logo.png", :alt => "Equipment Tracker", :class => "round")
  end
  
  def title
    base_title = "Equipment Tracker"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/equipment/_form.html.erb
<%= form_for(@equipment) do |f| %>
  <% if @equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

      <ul>
      <% @equipment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :equipment_id %><br />
    <%= f.text_field :equipment_id %>
  </div>
  <div class="field">
    <%= f.label :model_number %><br />
    <%= f.text_field :model_number %>
  </div>
  <div class="field">
    <%= f.label :serial_number %><br />
    <%= f.text_field :serial_number %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :equipment_description %><br />
    <%= f.text_area :equipment_description %>
  </div>
  <div class="field">
    <%= f.label :use %><br />
    <%= f.text_area :use %>
  </div>
  <div class="field">
    <%= f.label :department %><br />
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :po_number %><br />
    <%= f.text_field :po_number %>
  </div>
  <div class="field">
    <%= f.label :pm_required %><br />
    <%= f.text_field :pm_required %>
  </div>
  <div class="field">
    <%= f.label :maintenance_frequency %><br />
    <%= f.text_field :maintenance_frequency %>
  </div>
  <div class="field">
    <%= f.label :maintenance_sop %><br />
    <%= f.text_field :maintenance_sop %>
  </div>
  <div class="field">
    <%= f.label :calibration_required %><br />
    <%= f.check_box :calibration_required %>
  </div>
  <div class="field">
    <%= f.label :calibration_frequency %><br />
    <%= f.text_field :calibration_frequency %>
  </div>
  <div class="field">
    <%= f.label :calibration_date %><br />
    <%= f.date_select :calibration_date %>
  </div>
  <div class="field">
    <%= f.label :calibration_sticker %><br />
    <%= f.check_box :calibration_sticker %>
  </div>
  <div class="field">
    <%= f.label :calibration_database_update %><br />
    <%= f.check_box :calibration_database_update %>
  </div>
  <div class="field">
    <%= f.label :calibration_specs %><br />
    <%= f.text_field :calibration_specs %>
  </div>
  <div class="field">
    <%= f.label :validation_required %><br />
    <%= f.check_box :validation_required %>
  </div>
  <div class="field">
    <%= f.label :validation_sop %><br />
    <%= f.text_field :validation_sop %>
  </div>
  <div class="field">
    <%= f.label :validation_document %><br />
    <%= f.text_field :validation_document %>
  </div>
  <div class="field">
    <%= f.label :validation_approval %><br />
    <%= f.text_field :validation_approval %>
  </div>
  <div class ="field">
	<%= f.label :calibration_certificate %><br />
	<%= f.file_field :avatar %>
  </div>
  <div class ="field">
	<%= f.label :sop %><br />
	<%= f.file_field :sop %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipment/edit.html.erb
<h1>Editing equipment</h1>

<%= render 'form' %>

<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>

app/views/equipment/index.html.erb
<h1>Listing equipment</h1>

<table>
  <tr>
    <th>Equipment</th>
    <th>Model number</th>
    <th>Serial number</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @equipment.each do |equipment| %>
  <tr>
    <td><%= equipment.equipment_id %></td>
    <td><%= equipment.model_number %></td>
    <td><%= equipment.serial_number %></td>
    <td><%= equipment.location %></td>
    <td><%= link_to 'Show', equipment %></td>
    <td><%= link_to 'Edit', edit_equipment_path(equipment) %></td>
    <td><%= link_to 'Destroy', equipment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Equipment', new_equipment_path %>

app/views/equipment/new.html.erb
<h1>New equipment</h1>

<%= render 'form' %>

<%= link_to 'Back', equipment_index_path %>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Equipment:</b>
  <%= @equipment.equipment_id %>
</p>

<p>
  <b>Model number:</b>
  <%= @equipment.model_number %>
</p>

<p>
  <b>Serial number:</b>
  <%= @equipment.serial_number %>
</p>

<p>
  <b>Location:</b>
  <%= @equipment.location %>
</p>

<p>
  <b>Equipment description:</b>
  <%= @equipment.equipment_description %>
</p>

<p>
  <b>Use:</b>
  <%= @equipment.use %>
</p>

<p>
  <b>Department:</b>
  <%= @equipment.department %>
</p>

<p>
  <b>Po number:</b>
  <%= @equipment.po_number %>
</p>

<p>
  <b>Pm required:</b>
  <%= @equipment.pm_required %>
</p>

<p>
  <b>Maintenance frequency:</b>
  <%= @equipment.maintenance_frequency %>
</p>

<p>
  <b>Maintenance sop:</b>
  <%= @equipment.maintenance_sop %>
</p>

<p>
  <b>Calibration required:</b>
  <%= @equipment.calibration_required %>
</p>

<p>
  <b>Calibration frequency:</b>
  <%= @equipment.calibration_frequency %>
</p>

<p>
  <b>Calibration date:</b>
  <%= @equipment.calibration_date %>
</p>

<p>
  <b>Calibration sticker:</b>
  <%= @equipment.calibration_sticker %>
</p>

<p>
  <b>Calibration database update:</b>
  <%= @equipment.calibration_database_update %>
</p>

<p>
  <b>Calibration specs:</b>
  <%= @equipment.calibration_specs %>
</p>

<p>
  <b>Validation required:</b>
  <%= @equipment.validation_required %>
</p>

<p>
  <b>Validation sop:</b>
  <%= @equipment.validation_sop %>
</p>

<p>
  <b>Validation document:</b>
  <%= @equipment.validation_document %>
</p>

<p>
  <b>Validation approval:</b>
  <%= @equipment.validation_approval %>
</p>

<p>
<%= link_to "Calibration Certificate", @equipment.avatar.url(:original, false) %>
</p>

<p>
<%= link_to "Procedure (SOP)", @equipment.sop.url(:original, false) %>
</p>
<%= link_to 'Edit', edit_equipment_path(@equipment) %> |
<%= link_to 'Back', equipment_index_path %>

app/views/home/index.html.erb
<h1>Azzur Equipment Tracker</h1>
<%= link_to "Equipment", equipment_path %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Equipment", equipment_path %></li>
      <% end %>
	  <li><%= link_to "Help", help_path %></li>
	  <% if signed_in? %>
	  <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
	  <% else %>
	  <li><%= link_to "Sign in", signin_path %></li>
	  <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if 1t IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title><%= title %></title>
	<%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag :application %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			<section class="round">
				<% flash.each do |key, value| %>
					<%= content_tag(:div, value, :class => "flash #{key}") %>
				<% end %>
				<%= yield %>
			</section>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>